[package]
name = "frontend"
version = "0.1.0"
authors = ["Joshua Warner <joshw@dropbox.com>"]

[dependencies]
base64 = "0.9.2"
failure = "0.1.1"
futures-preview = "0.2.2"
liner = "0.4.4"
os_pipe = "0.6.1"
tokio = "0.1.7"
