cargo-features = ["edition"]

[package]
name = "protocol"
version = "0.1.0"
authors = ["Joshua Warner <joshw@dropbox.com>"]
edition = "2018"

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
failure = "0.1.1"
